name: Check that PRs are set to develop

on:
  pull_request_target:
   types: [opened, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Vankka/pr-target-branch-action@v1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target: main
          exclude: dev # Don't prevent going from develop -> master
          change-to: dev
          comment: |
            Your PR was set to `main`, but in this repository, PRs should be sent to `dev` instead.
            The base branch of this PR has been automatically changed to `dev`, please check that there are no merge conflicts and rebase as needed.
